// <auto-generated />
namespace Snake
{
    public partial class SnakeGame
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.title = new System.Windows.Forms.Label();
            this.insane = new System.Windows.Forms.Button();
            this.hard = new System.Windows.Forms.Button();
            this.medium = new System.Windows.Forms.Button();
            this.easy = new System.Windows.Forms.Button();
            this.newGame = new System.Windows.Forms.Button();
            this.gameTimer = new System.Windows.Forms.Timer(this.components);
            this.SuspendLayout();
            // 
            // title
            // 
            this.title.AutoSize = true;
            this.title.Font = new System.Drawing.Font("Microsoft Sans Serif", 48F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.title.Location = new System.Drawing.Point(80, 70);
            this.title.Name = "title";
            this.title.Size = new System.Drawing.Size(440, 73);
            this.title.TabIndex = 5;
            this.title.Text = "BZow\'s Snake";
            // 
            // insane
            // 
            this.insane.Location = new System.Drawing.Point(415, 308);
            this.insane.Name = "insane";
            this.insane.Size = new System.Drawing.Size(100, 40);
            this.insane.TabIndex = 4;
            this.insane.Text = "Insane";
            this.insane.UseVisualStyleBackColor = true;
            this.insane.Click += new System.EventHandler(this.Insane_Click);
            // 
            // hard
            // 
            this.hard.Location = new System.Drawing.Point(305, 308);
            this.hard.Name = "hard";
            this.hard.Size = new System.Drawing.Size(100, 40);
            this.hard.TabIndex = 3;
            this.hard.Text = "Hard";
            this.hard.UseVisualStyleBackColor = true;
            this.hard.Click += new System.EventHandler(this.Hard_Click);
            // 
            // medium
            // 
            this.medium.Location = new System.Drawing.Point(195, 308);
            this.medium.Name = "medium";
            this.medium.Size = new System.Drawing.Size(100, 40);
            this.medium.TabIndex = 2;
            this.medium.Text = "Medium";
            this.medium.UseVisualStyleBackColor = true;
            this.medium.Click += new System.EventHandler(this.Medium_Click);
            // 
            // easy
            // 
            this.easy.Location = new System.Drawing.Point(85, 308);
            this.easy.Name = "easy";
            this.easy.Size = new System.Drawing.Size(100, 40);
            this.easy.TabIndex = 1;
            this.easy.Text = "Easy";
            this.easy.UseVisualStyleBackColor = true;
            this.easy.Click += new System.EventHandler(this.Easy_Click);
            // 
            // newGame
            // 
            this.newGame.Location = new System.Drawing.Point(200, 200);
            this.newGame.Name = "newGame";
            this.newGame.Size = new System.Drawing.Size(200, 60);
            this.newGame.TabIndex = 0;
            this.newGame.Text = "Start Game";
            this.newGame.UseVisualStyleBackColor = true;
            this.newGame.Click += new System.EventHandler(this.NewGame_Click);
            // 
            // gameTimer
            // 
            this.gameTimer.Tick += new System.EventHandler(this.GameTimer_Tick);
            // 
            // SnakeGame
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(600, 400);
            this.Controls.Add(this.title);
            this.Controls.Add(this.insane);
            this.Controls.Add(this.hard);
            this.Controls.Add(this.medium);
            this.Controls.Add(this.easy);
            this.Controls.Add(this.newGame);
            this.DoubleBuffered = true;
            this.KeyPreview = true;
            this.Name = "SnakeGame";
            this.Text = "BZow\'s Snake";
            this.Paint += new System.Windows.Forms.PaintEventHandler(this.GameBoard_Paint);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.SnakeGame_KeyDown);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion     
 
        private System.Windows.Forms.Label title;
        private System.Windows.Forms.Button insane;
        private System.Windows.Forms.Button hard;
        private System.Windows.Forms.Button medium;
        private System.Windows.Forms.Button easy;
        private System.Windows.Forms.Button newGame;
        private System.Windows.Forms.Timer gameTimer;
    }
}